backend:
  name: github
  repo: Dealerpriest/obsklassen-website # Path to your Github repository
collections:
  - name: "test" # Used in routes, e.g., /admin/collections/blog
    label: "Testcollection" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "visas", name: "visas", widget: "boolean"} 
      - {label: "Content", name: "content", widget: "markdown"}