backend:
  name: git-gateway
collections:
  - name: "test" # Used in routes, e.g., /admin/collections/blog
    label: "Testcollection" # Used in the UI
    folder: "_test/teeest" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}